# Generated by Django 4.1.7 on 2023-04-20 00:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(blank=True, max_length=500),
        ),
    ]
